Repository hamlet-io/engine, pull requests merged in 2020-12, with the labels that each got.

#1473 fix(schema): metaparameters should not ref links
  providers/shared/views/schema/setup.ftl
Labels: documentation

#1476 Feature - Metaparameters as their own data type
  engine/bootstrap.ftl
  engine/inputdata/metaparameter.ftl
  engine/provider.ftl
  engine/schema.ftl
  providers/shared/metaparameters/links/id.ftl
  providers/shared/metaparameters/metaparameter.ftl
  providers/shared/views/schema/setup.ftl
Labels: enhancement

#1501 fix: erroneous bracket
  engine/occurrence.ftl
Labels: bug

#1505 fix: masterdata inclusion in blueprint
  engine/bootstrap.ftl
  engine/inputdata/blueprint.ftl
  engine/provider.ftl
Labels: bug
